### ISSUE TITLE
Invalid get index '35'

### ISSUE THREAD

**Issue by Abbychu** [qtren/myVNTemplate#1]
I have an issue right after the game wants to change scenes. I'll attatch some images for reference. It is a really interesting project, I hope you can still work on this template, I really want to make something with this soon.
![Captura de pantalla de 2021-06-28 04-00-34](https://user-images.githubusercontent.com/86591320/123594177-c8a94e00-d7c5-11eb-86ed-a41588e36b32.png)
![Captura de pantalla de 2021-06-28 04-00-42](https://user-images.githubusercontent.com/86591320/123594184-c9da7b00-d7c5-11eb-82bd-b93872f9282b.png)

I hope this helps in some way.

**Comment by qtren** [comment]
Hi there, this is an intended bug. 
It tells the editor that the script has reached the end of a conversation block, but there is no event to properly deal with the "ending". Try putting {'GDscene' : '/scenes/mainMenu.tscn'} to the end of main_block in the GDscript.

**Comment by qtren** [comment]
Btw, thank you very much for your interest. Currently, this template is a bit hard to use. I know... Trying my best to simplify some things
